version: '3.3'

services:
  database:
    image: postgres
    container_name: rentx_database
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - './.env.dev'
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  app:
    build: .
    container_name: rentx
    restart: always
    command: npm start
    depends_on:
      - database
    volumes:
      - ./dist:/usr/app/dist
    expose:
      - 3000
    ports:
      - 3000:3000
    network_mode: host

volumes:
  pgdata:
    driver: local
